In [2]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
from numba import jit
from tqdm.notebook import tqdm
import random

In [57]:
M=10000
N = 200
im_size = (N,N)

In [58]:
r = np.random.randint(2, size=(M,N,1))
print(np.shape(r))

(10000, 200, 1)


In [59]:
W = np.zeros((N,N))
for i in range(M):
    W += np.outer((r[i,:]-1/2),(r[i,:]-1/2))#finding weights based on image

In [60]:
print(np.shape(W))
np.fill_diagonal(W,0)
print(W)

(200, 200)
[[  0.  -11.   -9.5 ... -33.5  56.  -32. ]
 [-11.    0.   -0.5 ... -36.5   3.   20. ]
 [ -9.5  -0.5   0.  ...   8.    1.5 -47.5]
 ...
 [-33.5 -36.5   8.  ...   0.   56.5  20.5]
 [ 56.    3.    1.5 ...  56.5   0.  -24. ]
 [-32.   20.  -47.5 ...  20.5 -24.    0. ]]


In [61]:
#@jit(nopython=True)
def run(iterations,W,neurons,interval):
    neuron_iter = neurons
    for i in tqdm(range(iterations)):
        index = random.sample(range(0, len(neurons)), 100);
        selecW = W[index,:]
        selecW = selecW[:,index]
        neuron_iter[index] = np.dot(selecW,neuron_iter[index])>=0
    return neuron_iter

In [62]:
#create neural network with all neurons assigned 0/1 randomly with prob=0.5
#except for the first neurons which are set to the values of the image
to_use = r[0,:]

#neurons[0:int(nbits*.5)] = to_use[0:int(nbits*.5)]
#neurons[int(nbits*.7):nbits] = to_use[int(nbits*.7):nbits]
#plt.imshow(np.reshape(np.packbits(neurons[0:nbits]),im_size))

In [63]:
out = run(1000,W,to_use,10)

  0%|          | 0/1000 [00:00<?, ?it/s]

In [64]:
test = np.hstack((out,r[0,:]))
print(test)

[[0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]