In [1]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
from numba import jit
from tqdm.notebook import tqdm
import random

In [20]:
M = 1000
im_dim = 10
N = im_dim*im_dim
im_size = (im_dim,im_dim)
#img1 = cv2.resize(cv2.imread('monkey.png',0),im_size) #load monkey image as greyscale
#img2 = cv2.resize(cv2.imread('dog.png',0),im_size) #load dog image as greyscale

r = np.random.randint(2, size=(M,N))

In [21]:
W = np.zeros((N,N))
for i in range(M):
    W += np.outer((r[i]-1/2),(r[i]-1/2))#finding weights based on image

In [22]:
print(np.shape(W))
np.fill_diagonal(W,0)
print(W)

(100, 100)
[[ 0.   8.   7.5 ... -5.  -9.  -5.5]
 [ 8.   0.  -2.5 ...  4.  -4.  -4.5]
 [ 7.5 -2.5  0.  ...  1.5 -6.5  9. ]
 ...
 [-5.   4.   1.5 ...  0.   4.  -1.5]
 [-9.  -4.  -6.5 ...  4.   0.   9.5]
 [-5.5 -4.5  9.  ... -1.5  9.5  0. ]]


In [23]:
#@jit(nopython=True)
def run(iterations,W,neurons,interval):
    imgs_interval = []
    neurons_interval = []
    neuron_iter = neurons
    for i in tqdm(range(iterations)):
        index = random.sample(range(0, len(neurons)), 100);
        selecW = W[index,:]
        selecW = selecW[:,index]
        neuron_iter[index] = np.dot(selecW,neuron_iter[index])>=0
        if i%interval==0:
            imgs_interval.append(np.reshape(np.packbits(neuron_iter),im_size))
            neurons_interval.append(neuron_iter)
    return imgs_interval,neurons_interval

In [28]:
#create neural network with all neurons assigned 0/1 randomly with prob=0.5
#except for the first neurons which are set to the values of the image
neurons = r[0]
#neurons[0:int(nbits*.5)] = to_use[0:int(nbits*.5)]
#neurons[int(nbits*.7):nbits] = to_use[int(nbits*.7):nbits]
print(np.shape(neurons[0:N]))
plt.imshow(np.reshape(np.packbits(neurons[0:N]),(dim,dim)))

(100,)


ValueError: cannot reshape array of size 13 into shape (10,10)

In [25]:
imgs,neurons = run(1000,W,neurons,10)

  0%|          | 0/1000 [00:00<?, ?it/s]

ValueError: cannot reshape array of size 13 into shape (10,10)

In [ ]:
fig, axs = plt.subplots(1,4)
axs[0].imshow(imgs[0]);
axs[0].set_xticks([])
axs[0].set_yticks([])
axs[1].imshow(imgs[33]);
axs[1].set_xticks([])
axs[1].set_yticks([])
axs[2].imshow(imgs[66]);
axs[2].set_xticks([])
axs[2].set_yticks([])
axs[3].imshow(imgs[99]);
axs[3].set_xticks([])
axs[3].set_yticks([])

In [ ]:
err = (imgs[0]-imgs[99])>0
err = np.mean(err)
print(err)